In [72]:
import pandas as pd

In [73]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Roshani\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Roshani\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [74]:
import sys
print(sys.executable)

C:\Users\Roshani\AppData\Local\Programs\Python\Python314\python.exe

In [75]:
import pandas as pd

In [76]:
df = pd.read_csv("spotify_millsongdata.csv")

In [77]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [78]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [79]:
df.shape

(57650, 4)

In [80]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [81]:
df=df.sample(5000).drop('link',axis=1).reset_index(drop=True)

In [82]:
df.head(10)

,artist,song,text
0,Modern Talking,Last Exit To Brooklyn,I cannot sleep - the night is young \r\nI can...
1,Ramones,Somebody Put Something In My Drink,Another night out on the street \r\nStopping ...
2,Warren Zevon,Porcelain Monkey,He was an accident waiting to happen \r\nMost...
3,Isley Brothers,Let Me Down Easy,Is love behind me? \r\nThough I need you to s...
4,Neil Diamond,Kentucky Woman,Kentucky woman \r\nShe shines with her own ki...
5,George Jones,Big Fool Of The Year,All the big fools in town got together \r\nEv...
6,Rihanna,G4L,I lick the gun when I'm done \r\n'Cause I kno...
7,Peter Cetera,You Never Listen To Me,"You say not now, it's too late \r\nNow's not ..."
8,Noa,Me,Lyrics: Rachel \r\nMusic: Gil Dor \r\n \r\n...
9,Indiana Bible College,We've Come To Worship,Chorus \r\nWe've come to worship \r\nHonor a...

In [83]:
df['text'][0]

"I cannot sleep - the night is young  \r\nI cannot eat - I want some fun  \r\nI pick you up - Route 66  \r\nLife gives me the kick  \r\nI cannot live - I love this life  \r\nI cannot die - can I survive  \r\nI cannot breathe - without your love  \r\nI can't get enough  \r\n  \r\nIt's the last exit to Brooklyn  \r\nNew York City, oh is waiting  \r\nYou're a new boy, you're a party guy  \r\nBaby let's dance, and have some joy  \r\nWest coast, east side, that is the place where  \r\nNew York, L.A. I wanna live there  \r\nNew York City boy, L.A. party girl  \r\nBaby let's dance, in a brand new world  \r\n  \r\n4 - 6 - 0 - 1 - East Avenue  \r\nWhy does my heart - beats just for you  \r\nI cannot give - you more I'll give  \r\nBaby please forgive  \r\nI cannot tell - you thousant lies  \r\nI have the love - right in my eyes  \r\nThe night is young - I want your heart  \r\nBaby can we start  \r\n  \r\nIn between  \r\nHold on, baby, baby hold on  \r\nParty up, party up, party up, baby, party up, party up  \r\n  \r\nI can't believe - oh what I see  \r\nI can't control - it's extacy  \r\nI can't explain - oh what I feel  \r\nMy dream comes so real  \r\nI cannot leave - your love alone  \r\nI cannot go - I'm not a stone  \r\nI cannot say - good bye to you  \r\nWhen my dream comes true\r\n\r\n"

In [84]:
df.shape

(5000, 3)

In [85]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [86]:
df.tail(5)

,artist,song,text
4995,John Denver,Ripplin' Waters,i've got rippling waters to wake me to the mor...
4996,Doobie Brothers,Eyes Of Silver,eyes of silver hungry and aware \r eyes of si...
4997,Freddie King,You've Got To Love Her With A Feeling,now if you wanna love that woman \r you love ...
4998,Korn,One More Time,"always just coming in here, \r starts the gam..."
4999,Loretta Lynn,Slowly Killing Me,oh i can't live without you and i'm barely liv...

In [87]:
import nltk
from nltk.stem.porter import PorterStemmer

In [88]:
stemmer = PorterStemmer()

In [89]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in token]
    return " ".join(a)

In [90]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Roshani\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [91]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Roshani\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [92]:
token("you are beautiful, beauty")

'you are beauti , beauti'

In [93]:
df['text'].apply(lambda x: token(x))

0       i can not sleep - the night is young i can not...
1       anoth night out on the street stop for my usua...
2       he wa an accid wait to happen most accid happe...
3       is love behind me ? though i need you to satis...
4       kentucki woman she shine with her own kind of ...
                              ...
4995    i 've got rippl water to wake me to the morn ,...
4996    eye of silver hungri and awar eye of silver , ...
4997    now if you wan na love that woman you love her...
4998    alway just come in here , start the game whi c...
4999    oh i ca n't live without you and i 'm bare liv...
Name: text, Length: 5000, dtype: str

In [94]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Roshani\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

In [95]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [96]:
tfid = TfidfVectorizer(analyzer='word',stop_words='english')

In [97]:
matrix = tfid.fit_transform(df['text'])

In [98]:
similar = cosine_similarity(matrix)

In [99]:
similar[0]

array([1.        , 0.01088752, 0.00893958, ..., 0.09148006, 0.0215933 ,
       0.0606265 ], shape=(5000,))

In [104]:
df[df['song'] == 'Love Changes Everything']

Empty DataFrame
Columns: [artist, song, text]
Index: []

Recommender Function

In [110]:
def recommendation(song_name):
    result = df[df['song'].str.lower() == song_name.lower()]
    
    if result.empty:
        print("Song not found")
        return []
    
    idx = result.index[0]
    
    distances = sorted(
        list(enumerate(similar[idx])),
        reverse=True,
        key=lambda x: x[1]
    )
    
    songs = []
    for s_id in distances[1:5]:
        songs.append(df.iloc[s_id[0]].song)
    
    return songs

In [112]:
recommendation("Eyes Of Silver")

['Silver', 'My Baby', 'Silver Needles', 'Back In Your Own Backyard']

In [113]:
recommendation("Slowly Killing Me")

['Killing Me Softly With Her Song',
 "Passion's Killing Floor",
 'Killing',
 'Slowly Goes The Night']

In [114]:
import pickle

In [115]:
pickle.dump(similar,open("similar","wb"))

In [116]:
pickle.dump(df,open("df","wb"))